version: '3'
services:
  jsoc:
    build: .
    shm_size: 3G
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
